spring:
  profiles:
    active: dev
  application:
    name: groupweb2
  datasource:
    username: ${USER_NAME}
    password: ${PASSWORD}
    url: ${URL}
    driver-class-name: ${DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DIALECT}
        event:
          merge:
            entity_copy_observer: allow
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          sasl:
            enable: true
            mechanisms: XOAUTH2
          starttls:
            enable: true
            required: true


  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Ho_Chi_Minh
server:
  port: 8088

app:
  cors:
    allowOrigins: ${FRONT_END_URL}

