#DATASOURCE
USER_NAME: postgres
PASSWORD: Luudinhkien_2003
URL: jdbc:postgresql://localhost:5432/groupweb2
DRIVER: org.postgresql.Driver
DIALECT: org.hibernate.dialect.PostgreSQLDialect
FRONT_END_URL: http://localhost:4003

#Gmail
GMAIL_USERNAME: kienluu61@gmail.com
GMAIL_PASSWORD: abc